data:
  path: "data/finetune.csv"
  window_size: 20
  time_shift: 1
  start_preds_date: "2025-07-31" # начальная дата исключается из прогноза
  stop_preds_date: "2025-08-31" # конечная дата не исключается из прогноза

train:
  batch_size: 64
  lr: 0.01
  lr_fine: 0.0002
  epochs: 80

model:
  num_real_features: 22
  real_hidden_dim: 96
  complex_hidden_dim: 64
  dropout: 0.3
  n_res_blocks: 1
  seq_len: 20
  out_dim: 1